name = "sessy"
version = "0.1.0"
description = "User session management utilities for the Wisp web framework"
licences = ["Apache-2.0"]

repository = { type = "github", user = "pedraal", repo = "sessy" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
wisp = ">= 0.16.0 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
